name: ci
on: push

jobs:
  cheatsheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:11
      - name: Compile cheatsheet
        run: cs launch org.scalameta:mdoc_3:2.2.21 -- --in ReactiveCheatSheet.md